regen in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,3 +26,29 @@ jobs:
       - uses: dtolnay/rust-toolchain@1.74.0
       - name: Cargo check
         run: cargo check --workspace --all-targets
+  
+  generate-rust:
+    name: Generate Rust crate
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Clean
+        run: >
+          rm
+          src/xefg_swapchain/dx12.rs
+          src/xefg_swapchain/swapchain.rs
+          src/xell/dx12.rs
+          src/xell/xell.rs
+          src/xess/dx11.rs
+          src/xess/dx12.rs
+          src/xess/vk.rs
+          src/xess/xess.rs
+      - name: Generate
+        run: cargo b -Fgenerate-bindings
+      - name: Upload crate source
+        uses: actions/upload-artifact@v4
+        with:
+          name: crate-source
+          path: src/
+      - name: Diff generated Rust code
+        run: test -z "$(git status --porcelain -- '!.windows')" || (echo "::error::Generated files are different, please regenerate with cargo b -Fgenerate-bindings!"; git status; false)
